name: Fetch Trends

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch trends and write JSON
        env:
          CRON_TRENDS_URL: ${{ secrets.CRON_TRENDS_URL }}
        run: |
          set -euo pipefail
          if [ -z "${CRON_TRENDS_URL:-}" ]; then
            echo "CRON_TRENDS_URL secret not set. Please add it in repo settings." >&2
            exit 1
          fi
          mkdir -p data
          ts=$(date -u +'%Y%m%d-%H%M%S')
          curl -sS "$CRON_TRENDS_URL" -o "data/trends-${ts}.json"
          cp "data/trends-${ts}.json" data/latest.json
          echo "$ts" > data/.last_run

      - name: Commit and push if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(data): update trends ${GITHUB_SHA::7}"
            git push
          fi 